### ISSUE TITLE
Consolidate all YNAB converter scripts into just one?

### ISSUE THREAD

**Issue by torbengb** [PhantomOverride/ynab4-csv#2]
Hello Rennes!
I've noticed that there are more than 80 GitHub projects related to YNAB converter scripts. Would it be helpful and would there be interest in an effort to consolidate all (most) of these into a single tool? On the plus side, clearly there's more than enough solutions and contributors. On the minus side, these are spread across different spoken languages, programming languages, and of course bank export formats.

You're probably familiar with the YNAB subreddit. I've posted this idea here for a joint discussion: https://www.reddit.com/r/ynab/comments/75fctx/tools_can_we_consolidate_all_our_ynab_import/

Greetings from Vienna,
Ben

**Comment by PhantomOverride** [comment]
Hey @torbengb, thanks for getting in touch! I agree it could make things easier for the end user if someone consolidated all utilities into one mega-tool. I might be able to help you out with support for my bank, though I'll leave the rest of the project to you. Please let me know when/if things get started!

**Comment by torbengb** [comment]
I'm happy to hear from you!
We've already kicked things off. If you could provide the format information for your bank(s) that would be excellent. You could either edit this page
https://github.com/torbengb/bank2ynab/wiki/ImportFormats
or give me the values and I would add it there. 
Kind regards,
Ben
